/**
 * /data to /xapi Refactoring
 * These API endpoints are refactored from XNAT's endpoints in [/data, /service, and /AjaxServlet]
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@xnat.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class JsonParam (
  property: Option[String] = None,
  value: Option[SimpleString] = None
) extends ApiModel


